### ISSUE TITLE
Add missing documentation.

### ISSUE THREAD

**Issue by brylie** [lukejagodzinski/meteor-astronomy-forms#1]
The README mentions a documentation page for Astronomy Forms, but the page does not exist. Please add documentation.

**Comment by lukejagodzinski** [comment]
Hi. Package is under development and is not public yet until it will work. It's not even published on Atmosphere. I will let know when package can be tested.

**Comment by brylie** [comment]
Great! :-)

How does this package, and planned development timeline, compare with Aldeed Autoform? What would be some ways to combine with existing efforts?

**Comment by lukejagodzinski** [comment]
Right now you can check out how to use Astronomy with forms by going to meteor-astronomy-examples repo on my GitHub profile. And just read wiki page about validation.

There will be a package allowing usage of aldeed forms with astronomy. However this forms package will be the only one you will need. I don't know exact time when it will be ready. But I will notify about the progress. Just follow this and astronomy repos.

I'm on holiday right now and I will write more when I'm back :-)

**Comment by victorhooi** [comment]
Hi @jagi I do see the https://github.com/jagi/meteor-astronomy-examples repo.

I'm super excited about this project (Astronomy), and can't wait for the release of the forms page! =)

However, you also mentioned a wiki page on validation - are you able to provide a link for that page, or say which repo that wiki page is on please?

Or is there any other material available online on Astronomy, and what your vision for it is?

**Comment by lukejagodzinski** [comment]
Hi @victorhooi, thanks :)

The wiki page for Validators is located [here](https://github.com/jagi/meteor-astronomy/wiki/Validators) and [here](https://github.com/jagi/meteor-astronomy/wiki) is entire wiki page with the list of pages on the right.

Now, I know that moving some of the documentation to the wiki was the wrong choice. I will be preparing better documentation which will be posted on [this](http://astronomy.meteor.com/) website. The documentation will come out with the v1.0 release.

**Comment by 0o-de-lally** [comment]
@jagi Thanks for the initiative with this. I want to encourage you to release a draft of this just so we can give feedback. I've grown very frustrated with autoform, and was optimistic Astronomy might be a solution. Thanks in advance!

**Comment by lukejagodzinski** [comment]
I'm very close to releasing 1.0 of astronomy and after that I will focus mostly on forms package. However there is an issue on github when someone said that he is working on his forms package and he wants to integrate it with astronomy. So maybe while waiting on the official forms package you will be able to use that one.

**Comment by jimmy1993k** [comment]
What's the status of this form package? I can't seem to find any documentation on it anywhere and only tiny bits of information about it. Is this actually still coming to Astronomy 2.1?

**Comment by lukejagodzinski** [comment]
I'm probably not going to implement forms package as it's a big feature and I don't have time to manage one more project. However in 2.2 there will be a helper function that will simplify populating document with data coming from forms.
